name: Snyk vulnerability check 
on:
  pull_request:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
